export const ERROR = {
  ERROR_ADDRESS_NOT_FOUND: 'ERROR_ADDRESS_NOT_FOUND',
  ERROR_CIRCUIT_NOT_FOUND: 'ERROR_CIRCUIT_NOT_FOUND',
  ERROR_OPERATOR_INVALID_ADDRESS: 'ERROR_OPERATOR_INVALID_ADDRESS',
  ERROR_OPERATOR_NOT_FOUND: 'ERROR_OPERATOR_NOT_FOUND',
  ERROR_OPERATOR_DELAY_HISTORY_NOT_FOUND:
    'ERROR_OPERATOR_DELAY_HISTORY_NOT_FOUND',
  ERROR_QUERY_MISS_RATE_FAILED: 'ERROR_QUERY_MISS_RATE_FAILED',
  ERROR_OPERATORS_NOT_FOUND: 'ERROR_OPERATORS_NOT_FOUND',
  ERROR_PROOF_NOT_FOUND: 'ERROR_PROOF_NOT_FOUND',
  ERROR_ROUND_INVALID_ADDRESS: 'ERROR_ROUND_INVALID_ADDRESS',
  ERROR_ROUND_INVALID_STATUS: 'ERROR_ROUND_INVALID_STATUS',
  ERROR_ROUND_NOT_FOUND: 'ERROR_ROUND_NOT_FOUND',
  ERROR_ROUNDS_NOT_FOUND: 'ERROR_ROUNDS_NOT_FOUND',
  ERROR_TRANSACTION_NOT_FOUND: 'ERROR_TRANSACTION_NOT_FOUND',
  ERROR_TRANSACTIONS_NOT_FOUND: 'ERROR_TRANSACTIONS_NOT_FOUND',
  ERROR_SIGN_UP_EVENTS_NOT_FOUND: 'ERROR_SIGN_UP_EVENTS_NOT_FOUND',
};
